volumes:
  pg_data:

services:
  postgres:
    image: postgres:17
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend:
    image: dvidvi/project_store:latest
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres